title: Raymond Guo
author: guor8lei
subtitle: A brief look into my thoughts.

url: "https://guor8lei.github.io"
baseurl: "/blog"

footer_only_homepage: true
footer_url: "https://pro-panda.github.io/parchment/"
footer_text: "Inspired by Parchment theme by pro-panda."

favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
  style: compressed
  sass_dir: css

navbar:
  - name: "About"
    absolute-link: "https://guor8lei.github.io"
